- name: packages | Install common packages
  apt: pkg={{ item }} state=present
  with_items:
  - pmount
  - vim
  - avahi-daemon
  - libnss-mdns

- name: user | Setup user
  user: name={{ dlbox_user }} home={{ dlbox_prefix }} shell=/bin/false groups= createhome=no

- name: paths | Setup paths for dlbox user
  file: path={{ item.path }} state={{ item.state }} owner={{ dlbox_user }} group={{ dlbox_group }}
  with_items:
  - { path: "{{ dlbox_prefix}}", state: "directory" }
  - { path: "{{ dlbox_storage}}", state: "directory" }
